version: "3.7"

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    volumes:
      - "./statsd.config.js:/opt/statsd/config.js:ro"
      - "./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"
      - "./graphite:/opt/graphite/storage/:rw"
    ports:
      - "8080:8080"
      - "8125:8125/udp"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8081:3000"
    volumes:
      - "grafana_config:/var/lib/grafana"
    depends_on:
      - graphite

  # FIXME: Program metrics not received w/ cadvisor running
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.47.0
  #   command: >
  #     -storage_driver="statsd"
  #     -storage_driver_host="graphite:8125"
  #     -storage_driver_db="cadvisor"
  #     -storage_driver_buffer_duration="10s"
  #     --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,network
  #   depends_on:
  #     - graphite
  #   volumes:
  #     - "/:/rootfs:ro"
  #     - "/var/run:/var/run:rw"
  #     - "/sys:/sys:ro"
  #     - "/var/lib/docker/:/var/lib/docker:ro"
  #     - "/dev/disk/:/dev/disk:ro"
  #   devices:
  #     - "/dev/kmsg"

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8082:8081"
  worker:
    image: julia_worker
    tty: true
    stdin_open: true
    volumes:
      - "./src:/opt/app"
      - type: bind
        source: ./ips
        target: /opt/app/ips
        read_only: false
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=worker_{{.Task.Slot}}
      - TASK_SLOT={{.Task.Slot}}
    command: /bin/bash -c "echo $$(hostname -i) > /opt/app/ips/ip_$$TASK_SLOT.txt && /usr/sbin/sshd -D"

  manager:
    image: julia_manager
    tty: true
    stdin_open: true
    command: /bin/bash
    depends_on:
      - worker
    volumes:
      - "./src:/opt/app"
      - type: bind
        source: ./ips
        target: /opt/app/ips
        read_only: true
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=manager

volumes:
  grafana_config:
    external: true
