version: "3.7"

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    volumes:
      - "./statsd.config.js:/opt/statsd/config/udp.js:ro"
      - "./statsd.config.js:/opt/statsd/config/tcp.js:ro"
      - "./graphite.carbon.conf:/opt/graphite/conf/carbon.conf:ro"
      - "./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"
      - "./graphite:/opt/graphite/storage/:rw"
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: >
      -storage_driver="statsd"
      -storage_driver_host="graphite:8125"
      -storage_driver_db="cadvisor"
      -storage_driver_buffer_duration="1m0s"
      --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,network
    depends_on:
      - graphite
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: efoppiano/grafana:0.1
    ports:
      - "8081:3000"
    volumes:
      - "grafana_config:/var/lib/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    depends_on:
      - graphite
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  renderer:
    image: grafana/grafana-image-renderer:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  worker:
    image: julia_worker
    tty: true
    stdin_open: true
    volumes:
      - "./src:/opt/app"
      - "nfs_ips:/opt/app/ips"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=worker_{{.Task.Slot}}
      - TASK_SLOT={{.Task.Slot}}
    command: /bin/bash -c "echo $$(hostname -i) > /opt/app/ips/ip_$$TASK_SLOT.txt && /usr/sbin/sshd -D"

  manager:
    image: julia_manager
    tty: true
    stdin_open: true
    command: /bin/bash
    depends_on:
      - worker
    volumes:
      - "./src:/opt/app"
      - "nfs_ips:/opt/app/ips"
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=manager

volumes:
  grafana_config:
    external: true

  nfs_ips:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER_IP},nolock,soft,rw"
      device: ":/share1/ips"